"""empty message

Revision ID: ea8b8c1bce93
Revises: bc3a418e28f9
Create Date: 2022-09-12 09:23:15.479296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8b8c1bce93'
down_revision = 'bc3a418e28f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todolists SET completed = False WHERE completed IS NULL')
    op.alter_column('todolists', "completed", nullable = False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
